# frozen_string_literal: true

require "rake/extensiontask"
require "rake/testtask"

begin
  require "standard/rake"
rescue LoadError
  # standard gem not available — skip lint task
end

CROSS_PLATFORMS = %w[
  x86_64-linux
  aarch64-linux
  x86_64-darwin
  arm64-darwin
  x64-mingw-ucrt
].freeze

Rake::ExtensionTask.new("ml_dsa_ext") do |ext|
  ext.lib_dir = "lib/ml_dsa"
  ext.ext_dir = "ext/ml_dsa"
  ext.cross_compile = true
  ext.cross_platform = CROSS_PLATFORMS
end

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

namespace :gem do
  desc "Build native (fat) gems for all cross-compile platforms via rake-compiler-dock"
  task :cross do
    require "rake_compiler_dock"
    CROSS_PLATFORMS.each do |platform|
      RakeCompilerDock.sh("bundle && rake native:#{platform} gem", platform: platform)
    end
  end
end

namespace :vendor do
  desc "Update vendored PQClean sources from upstream (usage: rake vendor:update[COMMIT])"
  task :update, [:commit] do |_t, args|
    commit = args[:commit] || "main"
    tmpdir = "tmp/pqclean-update"

    sh "rm -rf #{tmpdir}"
    sh "git clone --depth 1 https://github.com/PQClean/PQClean.git #{tmpdir}"
    sh "cd #{tmpdir} && git checkout #{commit}" unless commit == "main"

    %w[44 65 87].each do |ps|
      src = "#{tmpdir}/crypto_sign/ml-dsa-#{ps}/clean"
      dst = "ext/ml_dsa/ml-dsa-#{ps}/clean"
      abort "ERROR: #{src} not found in PQClean checkout" unless File.directory?(src)
      sh "rm -rf #{dst}"
      sh "cp -R #{src} #{dst}"
    end

    # Record the vendored commit
    actual_sha = `cd #{tmpdir} && git rev-parse HEAD`.strip
    actual_date = `cd #{tmpdir} && git log -1 --format=%ci`.strip
    File.write("ext/ml_dsa/VENDORED_VERSION", <<~VER)
      pqclean
      commit: #{actual_sha}
      date: #{actual_date}
      url: https://github.com/PQClean/PQClean
      patches: patches/pqclean-explicit-rnd.patch
    VER

    sh "rm -rf #{tmpdir}"

    # Auto-apply patches and verify — no manual step required
    patch_file = "patches/pqclean-explicit-rnd.patch"
    if File.exist?(patch_file)
      puts "\n=== Applying #{patch_file} ==="
      sh "patch -p1 < #{patch_file}"
    else
      abort "ERROR: #{patch_file} not found — cannot apply required rnd_in patch"
    end

    puts "\n=== Vendored PQClean #{actual_sha[0..11]} ==="
    Rake::Task["pqclean:verify"].invoke
    puts "Vendor update complete — patches applied and verified."
  end
end

namespace :pqclean do
  desc "Verify vendored PQClean sources match the tracked patch"
  task :verify do
    variants = %w[44 65 87]
    prefix = "ext/ml_dsa/ml-dsa"
    modified_files = variants.flat_map do |v|
      ["#{prefix}-#{v}/clean/api.h",
        "#{prefix}-#{v}/clean/sign.h",
        "#{prefix}-#{v}/clean/sign.c"]
    end

    missing = modified_files.reject { |f| File.exist?(f) }
    abort "Missing source files: #{missing.join(", ")}" unless missing.empty?

    sign_patterns = [/const uint8_t \*rnd_in/, /memcpy\(rnd, rnd_in, RNDBYTES\)/]
    keygen_patterns = [/const uint8_t \*seed_in/, /memcpy\(seedbuf, seed_in, SEEDBYTES\)/]
    failures = []

    modified_files.each do |f|
      src = File.read(f, encoding: "binary")
      next if f.end_with?("api.h", "sign.h") && src.include?("rnd_in") && src.include?("seed_in")
      next if f.end_with?("sign.c") && sign_patterns.all? { |p| src.match?(p) } &&
        keygen_patterns.all? { |p| src.match?(p) }
      failures << f
    end

    if failures.empty?
      puts "pqclean:verify — all #{modified_files.size} patched files look correct."
    else
      abort "pqclean:verify FAILED — these files are missing expected patch content:\n  #{failures.join("\n  ")}"
    end
  end
end

begin
  require "yard"
  YARD::Rake::YardocTask.new do |t|
    t.files = ["lib/**/*.rb"]
    t.options = ["--markup", "markdown", "--output-dir", "doc"]
  end
rescue LoadError
  # yard gem not available — skip doc task
end

namespace :generate do
  desc "Regenerate ml_dsa_NN_impl.c amalgamation files from parametric template"
  task :impl do
    [44, 65, 87].each do |ps|
      path = "ext/ml_dsa/ml_dsa_#{ps}_impl.c"
      content = <<~C
        /*
         * ml_dsa_#{ps}_impl.c — ML-DSA-#{ps} amalgamation (PQClean clean implementation).
         *
         * AUTO-GENERATED by `rake generate:impl` — do not edit by hand.
         * Uses the parametric template: all PQClean sources are listed once
         * in ml_dsa_impl_template.h; this file just selects the parameter set.
         */

        #define ML_DSA_PS #{ps}
        #include "ml_dsa_impl_template.h"
      C
      File.write(path, content)
      puts "Generated #{path}"
    end
  end
end

desc "Run benchmarks for keygen, sign, and verify"
task bench: :compile do
  ruby "benchmark/bench.rb"
end

task test: :compile
task default: :test
