/*
 * ml_dsa_65_impl.c — ML-DSA-65 amalgamation (PQClean clean implementation).
 *
 * AUTO-GENERATED by `rake generate:impl` — do not edit by hand.
 * Uses the parametric template: all PQClean sources are listed once
 * in ml_dsa_impl_template.h; this file just selects the parameter set.
 */

#define ML_DSA_PS 65
#include "ml_dsa_impl_template.h"
